#3 - Add Database connection system and  #4 - Save the HVAC data in the database
RenaldMorino/oxygencs-grp1-eq5 pull request #21
Opened 2024-07-02 23:24 UTC by lanahria

# Description

Adding connection to the databse, sending Hvac data to it as well as logs from actions into the database.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-07-03 02:42 UTC, RenaldMorino commented on src/main.py
> +from urllib.parse import urlparse
Faudrait tu rajouter ça dans les dependencies du pipfile?

2024-07-03 02:43 UTC, RenaldMorino commented on src/main.py
> +from signalrcore.hub_connection_builder import HubConnectionBuilder
Pis ça?

2024-07-03 02:45 UTC, RenaldMorino approved these changes, later dismissed

2024-07-03 18:34 UTC, lanahria commented on src/main.py
> +from urllib.parse import urlparse
Oui ! J'avais oublié

2024-07-03 19:08 UTC, RenaldMorino submitted a review, later dismissed
Looks good

2024-07-04 17:04 UTC, Arachnight requested changes

2024-07-04 17:04 UTC, Arachnight commented on .gitignore
> +Pipfile.lock
Faut pas ignorer le Pipfile.loc

2024-07-04 17:57 UTC, lanahria commented on .gitignore
> +Pipfile.lock
Mais le pipeline fait pas un pipenv install ?
Si oui, ca sert a rien que ce fichier, generer et modifier par chaque utilisateur, soit sur le depot.

2024-07-04 18:24 UTC, Arachnight approved these changes

2024-07-04 20:22 UTC, merged